notifications:
  email: false

sudo: false

language: php

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

cache:
  directories:
    - vendor

install:
  - composer install -n

script:
  - composer test -- --coverage-clover=build/logs/clover.xml

after_success:
  - composer require php-coveralls/php-coveralls:^2
  - vendor/bin/php-coveralls -v
